codecov:
  branch: master

ignore:
  - "Kite-SDK/PSPrintSDK/AppDelegate*"
  - "Kite-SDK/PSPrintSDK/AssetDataSource*"
  - "Kite-SDK/PSPrintSDK/CI-ViewController*"
  - "Kite-SDK/PSPrintSDK/CustomAssetCollectionDataSource*"
  - "Kite-SDK/PSPrintSDK/LXReorderableCollectionViewFlowLayout*"
  - "Kite-SDK/PSPrintSDK/NSData+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/NSString+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/NSURL+OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/OLAnimation*"
  - "Kite-SDK/PSPrintSDK/OLCircularProgressView*"
  - "Kite-SDK/PSPrintSDK/OLFlipEnumerations*"
  - "Kite-SDK/PSPrintSDK/OLFlipTransition*"
  - "Kite-SDK/PSPrintSDK/OLFlipViewController*"
  - "Kite-SDK/PSPrintSDK/OLIndefiniteAnimatedView*"
  - "Kite-SDK/PSPrintSDK/OLKeyChainStore*"
  - "Kite-SDK/PSPrintSDK/OLMarkdownParser*"
  - "Kite-SDK/PSPrintSDK/OLOAuth2*"
  - "Kite-SDK/PSPrintSDK/OLProgressHUD*"
  - "Kite-SDK/PSPrintSDK/OLRadialGradientLayer*"
  - "Kite-SDK/PSPrintSDK/OLTransition*"
  - "Kite-SDK/PSPrintSDK/OLTransitionEnumerations*"
  - "Kite-SDK/PSPrintSDK/QREncoder"
  - "Kite-SDK/PSPrintSDK/RMImageCropper"
  - "Kite-SDK/PSPrintSDK/ViewController*"
  - "Kite-SDK/PSPrintSDK/main.m"
  - "Kite-SDK/PSPrintSDKTests/CompleteJourneyTests.m"
  - "Kite-SDK/PSPrintSDKTests/OLBaseRequest+Mock.m"
  - "Kite-SDK/PSPrintSDKTests/OLDocsObjcExampleCodeTests.m"
  - "Kite-SDK/PSPrintSDKTests/OLKiteRequestTests.m"
  - "Kite-SDK/PSPrintSDKTests/OLKiteTestHelper.m"
  - "Kite-SDK/PSPrintSDKTests/OLMockPanGestureRecognizer.*"
  - "Kite-SDK/PSPrintSDKTests/OLProductOrderTests.m"
  - "Kite-SDK/PSPrintSDKTests/OLSDKModelTests.m"
  - "Kite-SDK/PSPrintSDKTests/OLSwizzler.m"
  - "Kite-SDK/PSPrintSDKTests/OLTestTapGestureRecognizer.*"
  - "Kite-SDK/PSPrintSDKTests/UpsellTests.m"
  - "Kite-SDK/PSPrintSDKTests/ViewControllerTests.m"
  - "Kite-SDK/PSPrintSDKTests/XCTestCase+OLUITestMethods.m"
  - "Kite-SDK/PSPrintSDK/JDStatusBarNotification/JDStatusBarNotification.*"
  - "Kite-SDK/PSPrintSDK/JDStatusBarNotification/JDStatusBarStyle.*"
  - "Kite-SDK/PSPrintSDK/JDStatusBarNotification/JDStatusBarView.*"